// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rendezvous.proto

package sonm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// grpccmd imports
import (
	"io"

	"github.com/spf13/cobra"
	"github.com/sshaman1101/grpccmd"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// ConnectRequest describres a connection request to a remote target, possibly
// located under the NAT.
type ConnectRequest struct {
	// ID describes an unique ID of a target. Mainly it's an ETH address.
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	// Protocol describes network protocol the peer wants to resolve.
	Protocol string `protobuf:"bytes,2,opt,name=protocol" json:"protocol,omitempty"`
	// PrivateAddrs describes source private addresses.
	PrivateAddrs []*Addr `protobuf:"bytes,3,rep,name=privateAddrs" json:"privateAddrs,omitempty"`
}

func (m *ConnectRequest) Reset()                    { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string            { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()               {}
func (*ConnectRequest) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{0} }

func (m *ConnectRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ConnectRequest) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *ConnectRequest) GetPrivateAddrs() []*Addr {
	if m != nil {
		return m.PrivateAddrs
	}
	return nil
}

type PublishRequest struct {
	// Protocol describes network protocol the peer wants to publish.
	Protocol string `protobuf:"bytes,1,opt,name=protocol" json:"protocol,omitempty"`
	// PrivateAddrs describes source private addresses.
	PrivateAddrs []*Addr `protobuf:"bytes,2,rep,name=privateAddrs" json:"privateAddrs,omitempty"`
}

func (m *PublishRequest) Reset()                    { *m = PublishRequest{} }
func (m *PublishRequest) String() string            { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()               {}
func (*PublishRequest) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{1} }

func (m *PublishRequest) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *PublishRequest) GetPrivateAddrs() []*Addr {
	if m != nil {
		return m.PrivateAddrs
	}
	return nil
}

// RendezvousReply describes a rendezvous point reply.
type RendezvousReply struct {
	// PublicAddr is a public network address of a target.
	PublicAddr *Addr `protobuf:"bytes,1,opt,name=publicAddr" json:"publicAddr,omitempty"`
	// PrivateAddrs describes private network addresses of a target.
	//
	// These addresses should be used to perform an initial connection
	// attempt for cases where both peers are located under the same NAT.
	PrivateAddrs []*Addr `protobuf:"bytes,2,rep,name=privateAddrs" json:"privateAddrs,omitempty"`
}

func (m *RendezvousReply) Reset()                    { *m = RendezvousReply{} }
func (m *RendezvousReply) String() string            { return proto.CompactTextString(m) }
func (*RendezvousReply) ProtoMessage()               {}
func (*RendezvousReply) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{2} }

func (m *RendezvousReply) GetPublicAddr() *Addr {
	if m != nil {
		return m.PublicAddr
	}
	return nil
}

func (m *RendezvousReply) GetPrivateAddrs() []*Addr {
	if m != nil {
		return m.PrivateAddrs
	}
	return nil
}

// RendezvousState is a response returned from Info handle.
type RendezvousState struct {
	State map[string]*RendezvousMeeting `protobuf:"bytes,1,rep,name=state" json:"state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *RendezvousState) Reset()                    { *m = RendezvousState{} }
func (m *RendezvousState) String() string            { return proto.CompactTextString(m) }
func (*RendezvousState) ProtoMessage()               {}
func (*RendezvousState) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{3} }

func (m *RendezvousState) GetState() map[string]*RendezvousMeeting {
	if m != nil {
		return m.State
	}
	return nil
}

// RendezvousMeeting represents rendezvous point.
type RendezvousMeeting struct {
	Clients map[string]*RendezvousReply `protobuf:"bytes,1,rep,name=clients" json:"clients,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Servers map[string]*RendezvousReply `protobuf:"bytes,2,rep,name=servers" json:"servers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *RendezvousMeeting) Reset()                    { *m = RendezvousMeeting{} }
func (m *RendezvousMeeting) String() string            { return proto.CompactTextString(m) }
func (*RendezvousMeeting) ProtoMessage()               {}
func (*RendezvousMeeting) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{4} }

func (m *RendezvousMeeting) GetClients() map[string]*RendezvousReply {
	if m != nil {
		return m.Clients
	}
	return nil
}

func (m *RendezvousMeeting) GetServers() map[string]*RendezvousReply {
	if m != nil {
		return m.Servers
	}
	return nil
}

type ResolveMetaReply struct {
	IDs []string `protobuf:"bytes,1,rep,name=IDs" json:"IDs,omitempty"`
}

func (m *ResolveMetaReply) Reset()                    { *m = ResolveMetaReply{} }
func (m *ResolveMetaReply) String() string            { return proto.CompactTextString(m) }
func (*ResolveMetaReply) ProtoMessage()               {}
func (*ResolveMetaReply) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{5} }

func (m *ResolveMetaReply) GetIDs() []string {
	if m != nil {
		return m.IDs
	}
	return nil
}

func init() {
	proto.RegisterType((*ConnectRequest)(nil), "sonm.ConnectRequest")
	proto.RegisterType((*PublishRequest)(nil), "sonm.PublishRequest")
	proto.RegisterType((*RendezvousReply)(nil), "sonm.RendezvousReply")
	proto.RegisterType((*RendezvousState)(nil), "sonm.RendezvousState")
	proto.RegisterType((*RendezvousMeeting)(nil), "sonm.RendezvousMeeting")
	proto.RegisterType((*ResolveMetaReply)(nil), "sonm.ResolveMetaReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Rendezvous service

type RendezvousClient interface {
	// Resolve resolves the remote peer addresses.
	Resolve(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*RendezvousReply, error)
	// ResolveAll resolves remote servers using the specified peer ID,
	// returning the list of unique id's of these servets.
	//
	// Such UUIDs can be used for establishing aimed connection with all
	// servers under the same ID without randomization games.
	ResolveAll(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ResolveMetaReply, error)
	// Publish allows to publish the caller server's endpoints.
	//
	// While published the server can be located using the ID extracted from
	// the transport credentials.
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*RendezvousReply, error)
	// Info returns server's internal state.
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RendezvousState, error)
	Discover(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*DiscoverResponse, error)
}

type rendezvousClient struct {
	cc *grpc.ClientConn
}

func NewRendezvousClient(cc *grpc.ClientConn) RendezvousClient {
	return &rendezvousClient{cc}
}

func (c *rendezvousClient) Resolve(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*RendezvousReply, error) {
	out := new(RendezvousReply)
	err := grpc.Invoke(ctx, "/sonm.Rendezvous/Resolve", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rendezvousClient) ResolveAll(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ResolveMetaReply, error) {
	out := new(ResolveMetaReply)
	err := grpc.Invoke(ctx, "/sonm.Rendezvous/ResolveAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rendezvousClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*RendezvousReply, error) {
	out := new(RendezvousReply)
	err := grpc.Invoke(ctx, "/sonm.Rendezvous/Publish", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rendezvousClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RendezvousState, error) {
	out := new(RendezvousState)
	err := grpc.Invoke(ctx, "/sonm.Rendezvous/Info", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rendezvousClient) Discover(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*DiscoverResponse, error) {
	out := new(DiscoverResponse)
	err := grpc.Invoke(ctx, "/sonm.Rendezvous/Discover", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Rendezvous service

type RendezvousServer interface {
	// Resolve resolves the remote peer addresses.
	Resolve(context.Context, *ConnectRequest) (*RendezvousReply, error)
	// ResolveAll resolves remote servers using the specified peer ID,
	// returning the list of unique id's of these servets.
	//
	// Such UUIDs can be used for establishing aimed connection with all
	// servers under the same ID without randomization games.
	ResolveAll(context.Context, *ID) (*ResolveMetaReply, error)
	// Publish allows to publish the caller server's endpoints.
	//
	// While published the server can be located using the ID extracted from
	// the transport credentials.
	Publish(context.Context, *PublishRequest) (*RendezvousReply, error)
	// Info returns server's internal state.
	Info(context.Context, *Empty) (*RendezvousState, error)
	Discover(context.Context, *HandshakeRequest) (*DiscoverResponse, error)
}

func RegisterRendezvousServer(s *grpc.Server, srv RendezvousServer) {
	s.RegisterService(&_Rendezvous_serviceDesc, srv)
}

func _Rendezvous_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RendezvousServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Rendezvous/Resolve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RendezvousServer).Resolve(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rendezvous_ResolveAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RendezvousServer).ResolveAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Rendezvous/ResolveAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RendezvousServer).ResolveAll(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rendezvous_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RendezvousServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Rendezvous/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RendezvousServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rendezvous_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RendezvousServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Rendezvous/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RendezvousServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rendezvous_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RendezvousServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Rendezvous/Discover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RendezvousServer).Discover(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rendezvous_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sonm.Rendezvous",
	HandlerType: (*RendezvousServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Resolve",
			Handler:    _Rendezvous_Resolve_Handler,
		},
		{
			MethodName: "ResolveAll",
			Handler:    _Rendezvous_ResolveAll_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _Rendezvous_Publish_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Rendezvous_Info_Handler,
		},
		{
			MethodName: "Discover",
			Handler:    _Rendezvous_Discover_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rendezvous.proto",
}

// Begin grpccmd
var _ = grpccmd.RunE

// Rendezvous
var _RendezvousCmd = &cobra.Command{
	Use:   "rendezvous [method]",
	Short: "Subcommand for the Rendezvous service.",
}

var _Rendezvous_ResolveCmd = &cobra.Command{
	Use:   "resolve",
	Short: "Make the Resolve method call, input-type: sonm.ConnectRequest output-type: sonm.RendezvousReply",
	RunE: grpccmd.RunE(
		"Resolve",
		"sonm.ConnectRequest",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewRendezvousClient(cc)
		},
	),
}

var _Rendezvous_ResolveCmd_gen = &cobra.Command{
	Use:   "resolve-gen",
	Short: "Generate JSON for method call of Resolve (input-type: sonm.ConnectRequest)",
	RunE:  grpccmd.TypeToJson("sonm.ConnectRequest"),
}

var _Rendezvous_ResolveAllCmd = &cobra.Command{
	Use:   "resolveAll",
	Short: "Make the ResolveAll method call, input-type: sonm.ID output-type: sonm.ResolveMetaReply",
	RunE: grpccmd.RunE(
		"ResolveAll",
		"sonm.ID",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewRendezvousClient(cc)
		},
	),
}

var _Rendezvous_ResolveAllCmd_gen = &cobra.Command{
	Use:   "resolveAll-gen",
	Short: "Generate JSON for method call of ResolveAll (input-type: sonm.ID)",
	RunE:  grpccmd.TypeToJson("sonm.ID"),
}

var _Rendezvous_PublishCmd = &cobra.Command{
	Use:   "publish",
	Short: "Make the Publish method call, input-type: sonm.PublishRequest output-type: sonm.RendezvousReply",
	RunE: grpccmd.RunE(
		"Publish",
		"sonm.PublishRequest",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewRendezvousClient(cc)
		},
	),
}

var _Rendezvous_PublishCmd_gen = &cobra.Command{
	Use:   "publish-gen",
	Short: "Generate JSON for method call of Publish (input-type: sonm.PublishRequest)",
	RunE:  grpccmd.TypeToJson("sonm.PublishRequest"),
}

var _Rendezvous_InfoCmd = &cobra.Command{
	Use:   "info",
	Short: "Make the Info method call, input-type: sonm.Empty output-type: sonm.RendezvousState",
	RunE: grpccmd.RunE(
		"Info",
		"sonm.Empty",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewRendezvousClient(cc)
		},
	),
}

var _Rendezvous_InfoCmd_gen = &cobra.Command{
	Use:   "info-gen",
	Short: "Generate JSON for method call of Info (input-type: sonm.Empty)",
	RunE:  grpccmd.TypeToJson("sonm.Empty"),
}

var _Rendezvous_DiscoverCmd = &cobra.Command{
	Use:   "discover",
	Short: "Make the Discover method call, input-type: sonm.HandshakeRequest output-type: sonm.DiscoverResponse",
	RunE: grpccmd.RunE(
		"Discover",
		"sonm.HandshakeRequest",
		func(c io.Closer) interface{} {
			cc := c.(*grpc.ClientConn)
			return NewRendezvousClient(cc)
		},
	),
}

var _Rendezvous_DiscoverCmd_gen = &cobra.Command{
	Use:   "discover-gen",
	Short: "Generate JSON for method call of Discover (input-type: sonm.HandshakeRequest)",
	RunE:  grpccmd.TypeToJson("sonm.HandshakeRequest"),
}

// Register commands with the root command and service command
func init() {
	grpccmd.RegisterServiceCmd(_RendezvousCmd)
	_RendezvousCmd.AddCommand(
		_Rendezvous_ResolveCmd,
		_Rendezvous_ResolveCmd_gen,
		_Rendezvous_ResolveAllCmd,
		_Rendezvous_ResolveAllCmd_gen,
		_Rendezvous_PublishCmd,
		_Rendezvous_PublishCmd_gen,
		_Rendezvous_InfoCmd,
		_Rendezvous_InfoCmd_gen,
		_Rendezvous_DiscoverCmd,
		_Rendezvous_DiscoverCmd_gen,
	)
}

// End grpccmd

func init() { proto.RegisterFile("rendezvous.proto", fileDescriptor11) }

var fileDescriptor11 = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x5b, 0x6b, 0xdb, 0x30,
	0x14, 0x8e, 0x9d, 0x76, 0x4d, 0x4e, 0x4a, 0x9a, 0x89, 0x5d, 0x82, 0x9f, 0x82, 0xe9, 0x43, 0xd9,
	0xc5, 0x8c, 0x0c, 0x46, 0x19, 0x63, 0x50, 0xea, 0xc2, 0xfc, 0x50, 0x58, 0xd5, 0xd7, 0xbd, 0xb8,
	0xce, 0xd9, 0x6a, 0xaa, 0x48, 0x9e, 0xa5, 0x18, 0xbc, 0xdf, 0x32, 0xf6, 0x3f, 0xf6, 0xef, 0x86,
	0x2e, 0x4e, 0xed, 0xb4, 0xa1, 0x0c, 0xfa, 0x62, 0x1f, 0x1d, 0x7d, 0x97, 0xa3, 0x23, 0x1d, 0x98,
	0x94, 0xc8, 0x17, 0xf8, 0xab, 0x12, 0x2b, 0x19, 0x15, 0xa5, 0x50, 0x82, 0xec, 0x48, 0xc1, 0x97,
	0xc1, 0x41, 0xce, 0xf5, 0x9f, 0xe7, 0xa9, 0x4d, 0x07, 0xa3, 0x12, 0x59, 0x5a, 0xbb, 0xc5, 0x90,
	0xa3, 0xb2, 0x61, 0xc8, 0x60, 0x7c, 0x2a, 0x38, 0xc7, 0x4c, 0x51, 0xfc, 0xb9, 0x42, 0xa9, 0xc8,
	0x18, 0xfc, 0x24, 0x9e, 0x7a, 0x33, 0xef, 0x68, 0x48, 0xfd, 0x24, 0x26, 0x01, 0x0c, 0x0c, 0x34,
	0x13, 0x6c, 0xea, 0x9b, 0xec, 0x7a, 0x4d, 0x22, 0xd8, 0x2f, 0xca, 0xbc, 0x4a, 0x15, 0x9e, 0x2c,
	0x16, 0xa5, 0x9c, 0xf6, 0x67, 0xfd, 0xa3, 0xd1, 0x1c, 0x22, 0xed, 0x1d, 0xe9, 0x14, 0xed, 0xec,
	0x87, 0xdf, 0x60, 0xfc, 0x75, 0x75, 0xc5, 0x72, 0x79, 0xdd, 0xb8, 0xb5, 0xd5, 0xbd, 0x07, 0xd4,
	0xfd, 0x07, 0xd4, 0x97, 0x70, 0x40, 0xd7, 0xed, 0xa0, 0x58, 0xb0, 0x9a, 0xbc, 0x02, 0x28, 0xb4,
	0x61, 0xa6, 0x11, 0xc6, 0xa0, 0x2b, 0xd0, 0xda, 0xfd, 0x6f, 0xbb, 0xdf, 0x5e, 0xdb, 0xef, 0x52,
	0xa5, 0x0a, 0xc9, 0x07, 0xd8, 0x95, 0x3a, 0x98, 0x7a, 0x86, 0x3c, 0xb3, 0xe4, 0x0d, 0x54, 0x64,
	0xbe, 0x67, 0x5c, 0x95, 0x35, 0xb5, 0xf0, 0xe0, 0x02, 0xe0, 0x36, 0x49, 0x26, 0xd0, 0xbf, 0xc1,
	0xda, 0xf5, 0x43, 0x87, 0xe4, 0x2d, 0xec, 0x56, 0x29, 0x5b, 0xa1, 0xb9, 0x81, 0xd1, 0xfc, 0xe5,
	0xa6, 0xee, 0x39, 0xa2, 0xca, 0xf9, 0x0f, 0x6a, 0x51, 0x1f, 0xfd, 0x63, 0x2f, 0xfc, 0xeb, 0xc3,
	0xd3, 0x3b, 0x00, 0xf2, 0x19, 0xf6, 0x32, 0x96, 0x23, 0x57, 0xd2, 0x95, 0x78, 0xb8, 0x45, 0x2a,
	0x3a, 0xb5, 0x30, 0x5b, 0x66, 0x43, 0xd2, 0x7c, 0x89, 0x65, 0x85, 0xeb, 0xfe, 0x6c, 0xe5, 0x5f,
	0x5a, 0x98, 0xe3, 0x3b, 0x52, 0x70, 0x01, 0xfb, 0x6d, 0xe1, 0x7b, 0x8e, 0xfa, 0xba, 0x7b, 0xd4,
	0xe7, 0x9b, 0xfa, 0xe6, 0x62, 0x5b, 0x07, 0xd5, 0x92, 0x6d, 0xaf, 0x47, 0x90, 0x0c, 0x0f, 0x61,
	0x42, 0x51, 0x0a, 0x56, 0xe1, 0x39, 0xaa, 0xd4, 0x3e, 0xa5, 0x09, 0xf4, 0x93, 0xd8, 0x76, 0x6d,
	0x48, 0x75, 0x38, 0xff, 0xe3, 0x03, 0xdc, 0x8a, 0x90, 0x63, 0xd8, 0x73, 0x24, 0xf2, 0xcc, 0x3a,
	0x74, 0x27, 0x2b, 0xb8, 0xdf, 0x37, 0xec, 0x91, 0x77, 0x5a, 0xc7, 0x30, 0x4f, 0x18, 0x23, 0x03,
	0x0b, 0x4b, 0xe2, 0xe0, 0x45, 0x43, 0xe8, 0x96, 0x12, 0xf6, 0xb4, 0x97, 0x1b, 0xa4, 0xc6, 0xab,
	0x3b, 0x57, 0xdb, 0xbd, 0xde, 0xc0, 0x4e, 0xc2, 0xbf, 0x0b, 0x32, 0xb2, 0x80, 0xb3, 0x65, 0xa1,
	0xea, 0xbb, 0x68, 0xf3, 0x18, 0xc3, 0x1e, 0xf9, 0x04, 0x83, 0x38, 0x97, 0x99, 0xa8, 0xb0, 0x24,
	0xae, 0x9a, 0x2f, 0x29, 0x5f, 0xc8, 0xeb, 0xf4, 0x06, 0x1b, 0x2b, 0x97, 0x6f, 0x70, 0x14, 0x65,
	0x21, 0xb8, 0xc4, 0xb0, 0x77, 0xf5, 0xc4, 0x8c, 0xf2, 0xfb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x1d, 0xb8, 0xef, 0x42, 0xa6, 0x04, 0x00, 0x00,
}
